version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/frontend/web"
    schedule:
      interval: "monthly"
    commit-message:
      prefix: "[web] "
  - package-ecosystem: "pip"
    directory: "/backend"
    schedule:
      interval: "monthly"
    commit-message:
      prefix: "[api] "
  - package-ecosystem: "docker"
    directories:
      - "/frontend"
      - "/backend"
    schedule:
      interval: "monthly"
    commit-message:
      prefix: "[docker] "
