---
services:
  ansible-tester-api:
    build:
      context: backend
      dockerfile: Dockerfile
    container_name: api
    ports:
      - 8000:8000
    volumes:
      - ./backend/api:/src
    networks:
      - ansible-tester

networks:
  ansible-tester:
    driver: bridge
